[2023-08-16T20:02:23.316+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-08-16T20:02:23.329+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-14T00:00:00+00:00 [queued]>
[2023-08-16T20:02:23.330+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:23.332+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T20:02:23.333+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:23.344+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-14 00:00:00+00:00
[2023-08-16T20:02:23.351+0000] {standard_task_runner.py:55} INFO - Started process 2225 to run task
[2023-08-16T20:02:23.356+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-14T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmp5qqntzin']
[2023-08-16T20:02:23.357+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask extract_relevant_credentials
[2023-08-16T20:02:23.431+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-14T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T20:02:23.575+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-14T00:00:00+00:00
[2023-08-16T20:02:23.580+0000] {python.py:177} INFO - Done. Returned value was: (['Arlo', 'Rosa', 'کوروش', 'Camila', 'Edmund', 'Donald', 'ثنا', 'Andrea', 'Daniella', 'Wesley'], ['Lee', 'Robinson', 'گلشن', 'Richardson', 'Bang', 'Gibson', 'احمدی', 'Castillo', 'Grøndal', 'Fields'], ['male', 'female', 'male', 'female', 'male', 'male', 'female', 'female', 'female', 'male'], ['arlo.lee@example.com', 'rosa.robinson@example.com', 'khwrwsh.glshn@example.com', 'camila.richardson@example.com', 'edmund.bang@example.com', 'donald.gibson@example.com', 'thn.hmdy@example.com', 'andrea.castillo@example.com', 'daniella.grondal@example.com', 'wesley.fields@example.com'], [datetime.date(1964, 4, 13), datetime.date(1961, 8, 11), datetime.date(1977, 8, 26), datetime.date(1952, 10, 3), datetime.date(1951, 5, 22), datetime.date(1961, 7, 10), datetime.date(1948, 7, 31), datetime.date(1972, 4, 2), datetime.date(1970, 6, 27), datetime.date(1990, 8, 23)], ['New Zealand', 'Australia', 'Iran', 'Australia', 'Norway', 'Ireland', 'Iran', 'United Kingdom', 'Norway', 'Ireland'], ['House 8044, Panama Road', 'House 7170, Eason Rd', 'House 4551, 17 شهریور', 'House 9717, Lakeshore Rd', 'House 6185, Åsensvingen', 'House 2143, The Avenue', 'House 5819, قائم مقام فراهانی', 'House 1638, Chester Road', 'House 6, Ugleveien', 'House 7033, High Street'], ['Tauranga', 'Bunbury', 'قدس', 'Albury', 'Midsund', 'Athy', 'قزوین', 'Leicester', 'Haugesund', 'Kilcock'], ["Hawke'S Bay", 'Queensland', 'تهران', 'New South Wales', 'Description', 'Roscommon', 'چهارمحال و بختیاری', 'West Sussex', 'Akershus', 'Wexford'], [95886, 2868, 52909, 4234, '0608', 39511, 36884, 'TG5 2LS', '6092', 70765], ['(550)-895-0200', '08-5391-5798', '041-26759452', '06-8267-7390', '84646388', '071-488-9846', '019-34247696', '023 6182 5882', '60737395', '031-767-6582'], ['(474)-533-3863', '0487-478-787', '0904-394-2340', '0441-540-459', '95388762', '081-836-2385', '0929-069-3550', '07653 447398', '45807696', '081-037-0334'])
[2023-08-16T20:02:23.589+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T20:02:23.601+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230814T000000, start_date=20230816T200223, end_date=20230816T200223
[2023-08-16T20:02:23.611+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 2225)
[2023-08-16T20:02:23.653+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T20:02:23.676+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
