[2023-08-16T20:02:12.157+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-16T20:02:12.187+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-01T00:00:00+00:00 [queued]>
[2023-08-16T20:02:12.188+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:12.189+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T20:02:12.191+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T20:02:12.215+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-01 00:00:00+00:00
[2023-08-16T20:02:12.223+0000] {standard_task_runner.py:55} INFO - Started process 2208 to run task
[2023-08-16T20:02:12.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-01T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmpzouec9lt']
[2023-08-16T20:02:12.237+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask extract_relevant_credentials
[2023-08-16T20:02:12.328+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-01T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T20:02:12.496+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-01T00:00:00+00:00
[2023-08-16T20:02:12.500+0000] {python.py:177} INFO - Done. Returned value was: (['Viivi', 'Gaël', 'Zoe', 'Humberto', 'Ekansh', 'Volkan', 'Rolf', 'Sakarias', 'Alfredo', 'Janko'], ['Niemi', 'Gauthier', 'Wong', 'Patiño', 'Gupta', 'Egeli', 'Motz', 'Hegre', 'Patiño', 'Ignjatović'], ['female', 'male', 'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male'], ['viivi.niemi@example.com', 'gael.gauthier@example.com', 'zoe.wong@example.com', 'humberto.patino@example.com', 'ekansh.gupta@example.com', 'volkan.egeli@example.com', 'rolf.motz@example.com', 'sakarias.hegre@example.com', 'alfredo.patino@example.com', 'janko.ignjatovic@example.com'], [datetime.date(1954, 2, 5), datetime.date(1975, 10, 31), datetime.date(1976, 6, 13), datetime.date(1955, 1, 20), datetime.date(1972, 12, 12), datetime.date(1975, 10, 10), datetime.date(1994, 9, 10), datetime.date(1991, 10, 19), datetime.date(1980, 12, 13), datetime.date(1964, 1, 16)], ['Finland', 'France', 'Canada', 'Mexico', 'India', 'Turkey', 'Germany', 'Norway', 'Mexico', 'Serbia'], ['House 421, Mechelininkatu', 'House 2617, Rue Principale', 'House 1614, Grand Ave', 'House 6592, Andador Bangladesh', 'House 6039, Rajaji Salai', 'House 7284, Vatan Cd', 'House 1599, Kirchplatz', 'House 5622, Kaiekroken', 'House 3521, Eje vial Guerrero', 'House 8533, Nikole Nikolajevića'], ['Vimpeli', 'Colombes', 'Russell', 'Petacalco', 'Bhavnagar', 'Batman', 'Annweiler am Trifels', 'Bremanger', 'Las Cañadas', 'Ljubovija'], ['North Karelia', 'Gers', 'Saskatchewan', 'Oaxaca', 'Karnataka', 'Çanakkale', 'Bremen', 'Møre og Romsdal', 'Estado de Mexico', 'Kosovo-Pomoravlje'], [59399, 68591, 'T7A 9L4', 58505, 73058, 70536, 75678, '3039', 22180, 92749], ['09-764-037', '02-55-27-89-69', 'P84 N57-4338', '(611) 344 5095', '9715324051', '(668)-040-5331', '0797-7683512', '28572105', '(661) 857 7037', '018-6502-230'], ['040-065-61-07', '06-79-53-78-96', 'L93 N36-0466', '(657) 174 0969', '7366686453', '(847)-301-4658', '0173-1232705', '43347516', '(654) 011 5820', '065-9305-202'])
[2023-08-16T20:02:12.513+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T20:02:12.528+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230801T000000, start_date=20230816T200212, end_date=20230816T200212
[2023-08-16T20:02:12.540+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 2208)
[2023-08-16T20:02:12.563+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T20:02:12.592+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
