[2023-08-16T19:57:29.159+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-04T00:00:00+00:00 [queued]>
[2023-08-16T19:57:29.168+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-04T00:00:00+00:00 [queued]>
[2023-08-16T19:57:29.170+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:29.171+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T19:57:29.172+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:29.183+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-04 00:00:00+00:00
[2023-08-16T19:57:29.190+0000] {standard_task_runner.py:55} INFO - Started process 1839 to run task
[2023-08-16T19:57:29.200+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-04T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmph2u2oq2m']
[2023-08-16T19:57:29.202+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask extract_relevant_credentials
[2023-08-16T19:57:29.271+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-04T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T19:57:29.401+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-04T00:00:00+00:00
[2023-08-16T19:57:29.405+0000] {python.py:177} INFO - Done. Returned value was: (['Albert', 'Ianis', 'Minea', 'عسل', 'Homero', 'Oliver', 'Tyrone', 'Grazyna', 'Emily', 'Mehar'], ['Madsen', 'Cavalcanti', 'Halonen', 'محمدخان', 'Luevano', 'Wallo', 'Hill', 'Bellmann', 'Olsen', 'Bhat'], ['male', 'male', 'female', 'female', 'male', 'male', 'male', 'female', 'female', 'female'], ['albert.madsen@example.com', 'ianis.cavalcanti@example.com', 'minea.halonen@example.com', 'aasl.mhmdkhn@example.com', 'homero.luevano@example.com', 'oliver.wallo@example.com', 'tyrone.hill@example.com', 'grazyna.bellmann@example.com', 'emily.olsen@example.com', 'mehar.bhat@example.com'], [datetime.date(2000, 10, 29), datetime.date(1963, 12, 15), datetime.date(1983, 11, 30), datetime.date(1994, 8, 25), datetime.date(1945, 11, 16), datetime.date(1984, 8, 10), datetime.date(1971, 12, 30), datetime.date(1976, 9, 20), datetime.date(2001, 1, 12), datetime.date(1947, 4, 12)], ['Denmark', 'Brazil', 'Finland', 'Iran', 'Mexico', 'Finland', 'United Kingdom', 'Germany', 'Denmark', 'India'], ['House 5544, Bogfinkevej', 'House 3859, Rua São Paulo ', 'House 8037, Verkatehtaankatu', 'House 5913, میدان شهیدان رحیمی', 'House 1029, Viaducto Tirado', 'House 7194, Satakennankatu', 'House 7193, North Road', 'House 7845, Kapellenweg', 'House 3513, Odinsvej', 'House 1455, Ashoka Rd'], ['Ugerløse', 'Santa Cruz do Sul', 'Enontekiö', 'ساری', 'Pantelho', 'Vesilahti', 'Coventry', 'Heidenheim an der Brenz', 'Ishoej', 'Hapur'], ['Nordjylland', 'Ceará', 'Kymenlaakso', 'اصفهان', 'Oaxaca', 'Satakunta', 'Somerset', 'Niedersachsen', 'Nordjylland', 'Bihar'], [98134, 25955, 70016, 22375, 10271, 86662, 'CS95 6EJ', 19070, 82627, 80713], ['24029787', '(94) 3759-8891', '06-868-077', '081-09024263', '(613) 580 1877', '07-788-949', '019467 87097', '0891-1086528', '27192067', '8378861750'], ['12673092', '(96) 0733-6160', '044-577-54-75', '0939-102-3872', '(665) 575 3879', '043-077-40-14', '07569 373991', '0178-7800139', '21394321', '8125989298'])
[2023-08-16T19:57:29.415+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T19:57:29.427+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230804T000000, start_date=20230816T195729, end_date=20230816T195729
[2023-08-16T19:57:29.436+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 1839)
[2023-08-16T19:57:29.495+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T19:57:29.518+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
