[2023-08-16T19:57:30.635+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-16T19:57:30.651+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-08T00:00:00+00:00 [queued]>
[2023-08-16T19:57:30.652+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:30.653+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-08-16T19:57:30.656+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-08-16T19:57:30.671+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_relevant_credentials> on 2023-08-08 00:00:00+00:00
[2023-08-16T19:57:30.679+0000] {standard_task_runner.py:55} INFO - Started process 1841 to run task
[2023-08-16T19:57:30.692+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'random_user_v1', 'extract_relevant_credentials', 'scheduled__2023-08-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/random_user_etl.py', '--cfg-path', '/tmp/tmpojv_0o71']
[2023-08-16T19:57:30.694+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask extract_relevant_credentials
[2023-08-16T19:57:30.782+0000] {task_command.py:389} INFO - Running <TaskInstance: random_user_v1.extract_relevant_credentials scheduled__2023-08-08T00:00:00+00:00 [running]> on host c0eab1525b89
[2023-08-16T19:57:30.935+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mujjeeb
AIRFLOW_CTX_DAG_ID=random_user_v1
AIRFLOW_CTX_TASK_ID=extract_relevant_credentials
AIRFLOW_CTX_EXECUTION_DATE=2023-08-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-08T00:00:00+00:00
[2023-08-16T19:57:30.940+0000] {python.py:177} INFO - Done. Returned value was: (['Uwe', 'Dana', 'Laura', 'Catalina', 'Bobby', 'Jeffery', 'Eskil', 'Brendan', 'Pierre', 'Tyler'], ['Jean', 'Hunt', 'Olsen', 'Ortega', 'Wagner', 'Coleman', 'Seeberg', 'Curtis', 'Renaud', 'Harris'], ['male', 'female', 'female', 'female', 'male', 'male', 'male', 'male', 'male', 'male'], ['uwe.jean@example.com', 'dana.hunt@example.com', 'laura.olsen@example.com', 'catalina.ortega@example.com', 'bobby.wagner@example.com', 'jeffery.coleman@example.com', 'eskil.seeberg@example.com', 'brendan.curtis@example.com', 'pierre.renaud@example.com', 'tyler.harris@example.com'], [datetime.date(1956, 11, 26), datetime.date(1956, 7, 31), datetime.date(1975, 10, 13), datetime.date(1995, 10, 29), datetime.date(1949, 1, 4), datetime.date(1992, 7, 20), datetime.date(1972, 9, 18), datetime.date(1986, 9, 22), datetime.date(1955, 11, 2), datetime.date(1984, 3, 24)], ['Switzerland', 'United States', 'Denmark', 'Spain', 'Australia', 'United Kingdom', 'Norway', 'Ireland', 'France', 'New Zealand'], ['House 9046, Rue Bony', 'House 2110, Mockingbird Hill', 'House 7008, Stengade', 'House 3933, Calle de Bravo Murillo', 'House 2465, E Sandy Lake Rd', 'House 5749, Main Road', 'House 2695, Langengen', "House 2189, O'Connell Avenue", 'House 6009, Avenue Paul Eluard', 'House 6893, Symonds Street'], ['Féchy', 'Caldwell', 'Hornbæk', 'Móstoles', 'Orange', 'Coventry', 'Skarnes', 'Newbridge', 'Montpellier', 'Nelson'], ['Valais', 'Maryland', 'Hovedstaden', 'Navarra', 'Western Australia', 'Suffolk', 'Vestfold', 'Galway City', 'Aude', 'Bay of Plenty'], [4557, 70738, 11167, 47190, 7545, 'H78 3JJ', '1601', 65862, 32335, 28311], ['075 319 84 98', '(616) 915-9459', '48806834', '911-376-256', '03-9720-7972', '015395 72826', '69498892', '041-635-5127', '02-20-95-34-25', '(018)-692-7661'], ['077 685 78 81', '(892) 837-2552', '42010933', '660-069-413', '0456-444-914', '07703 283850', '98337227', '081-658-5105', '06-87-38-79-29', '(958)-766-7097'])
[2023-08-16T19:57:30.950+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2301, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.date' object has no attribute '__module__'
[2023-08-16T19:57:30.964+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_v1, task_id=extract_relevant_credentials, execution_date=20230808T000000, start_date=20230816T195730, end_date=20230816T195730
[2023-08-16T19:57:30.975+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task extract_relevant_credentials ('datetime.date' object has no attribute '__module__'; 1841)
[2023-08-16T19:57:31.016+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-08-16T19:57:31.063+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
